### ISSUE TITLE
你这里也没用到smart-socket呀

### ISSUE THREAD

**Issue by micky2333** [NaTieJun/orise-charge-cloud#1]
你这里也没用到smart-socket呀，还感谢smart-socket干嘛呀

**Comment by NaTieJun** [comment]
原来版本是有的，不过通信协议部分比较商业化，在国内开源平台被投诉导致整个项目被禁了，所以干脆整个tcp模块全下掉了，tcp通信重构成了http协议来模拟桩通信；目前商业版使用smart-socket做为通信框架，通过我们二次迭代更新达到了非常高的性能，4核4G的单服务器可以支持1万桩在线和1.5k桩同时充电，所以即便开源版没有smart-socket，我们也要感谢
