### ISSUE TITLE
请问开源版有中电联互联互通协议的实现吗？

### ISSUE THREAD

**Issue by xuyechuan** [NaTieJun/orise-charge-cloud#6]
非常好的项目，请问开源版有中电脸互联互通协议的实现吗？

**Comment by xuyechuan** [comment]
哦，通过搜索AESUtils.aes128CbcPKCS5Padding的用法找到了hlht的目录，感谢分享
希望有时间文档可以再完善些呢

**Comment by NaTieJun** [comment]
好的 我们忙完这阵子就开始疯狂补文档哈
